#
# Makefile for the Linux Kernel SOC fsl specific device drivers
#

obj-$(CONFIG_FSL_DPAA)                 += qbman/
obj-$(CONFIG_QUICC_ENGINE)		+= qe/
obj-$(CONFIG_CPM)			+= qe/
obj-$(CONFIG_FSL_QIXIS) 		+= qixis_ctrl.o
obj-$(CONFIG_FSL_GUTS)			+= guts.o
obj-$(CONFIG_FSL_MC_DPIO) 		+= dpio/
obj-$(CONFIG_FSL_LS2_CONSOLE)		+= ls2-console/
obj-$(CONFIG_FSL_SLEEP_FSM)	+= sleep_fsm.o
