/* micm_cfg: Instruction Cache/Memory Configuration Register */
#define MICM_CFG 0xfc0

#define MICM_CFG_ISET_OFFSET		0
#define MICM_CFG_IWAY_OFFSET		3
#define MICM_CFG_ISZ_OFFSET		6
#define MICM_CFG_ILCK_OFFSET		9
#define MICM_CFG_IC_ECC_OFFSET		10
#define MICM_CFG_ILMB_OFFSET		12
#define MICM_CFG_ILMSZ_OFFSET		15
#define MICM_CFG_ULM_2BANK_OFFSET	20
#define MICM_CFG_ILM_ECC_OFFSET		21


#define MICM_CFG_ISET_MASK	(0x7  << MICM_CFG_ISET_OFFSET)
#define MICM_CFG_IWAY_MASK	(0x7  << MICM_CFG_IWAY_OFFSET)
#define MICM_CFG_ISZ_MASK	(0x7  << MICM_CFG_ISZ_OFFSET)
#define MICM_CFG_ILCK_MASK	(0x1  << MICM_CFG_ILCK_OFFSET)
#define MICM_CFG_IC_ECC_MASK	(0x3  << MICM_CFG_IC_ECC_OFFSET)
#define MICM_CFG_ILMB_MASK	(0x7  << MICM_CFG_ILMB_OFFSET)
#define MICM_CFG_ILMSZ_MASK	(0x1f << MICM_CFG_ILMSZ_OFFSET)
#define MICM_CFG_ULM_2BANK_MASK	(0x1  << MICM_CFG_ULM_2BANK_OFFSET)
#define MICM_CFG_ILM_ECC_MASK	(0x3  << MICM_CFG_ILM_ECC_OFFSET)

/* mdcm_cfg: Data Cache/Memory Configuration Register */
#define MDCM_CFG 0xfc1

#define MDCM_CFG_DSET_OFFSET		0
#define MDCM_CFG_DWAY_OFFSET		3
#define MDCM_CFG_DSZ_OFFSET		6
#define MDCM_CFG_DLCK_OFFSET		9
#define MDCM_CFG_DC_ECC_OFFSET		10
#define MDCM_CFG_DLMB_OFFSET		12
#define MDCM_CFG_DLMSZ_OFFSET		15
#define MDCM_CFG_ULM_2BANK_OFFSET	20
#define MDCM_CFG_DLM_ECC_OFFSET		21


#define MDCM_CFG_DSET_MASK	(0x7  << MDCM_CFG_DSET_OFFSET)
#define MDCM_CFG_DWAY_MASK	(0x7  << MDCM_CFG_DWAY_OFFSET)
#define MDCM_CFG_DSZ_MASK	(0x7  << MDCM_CFG_DSZ_OFFSET)
#define MDCM_CFG_DLCK_MASK	(0x1  << MDCM_CFG_DLCK_OFFSET)
#define MDCM_CFG_DC_ECC_MASK	(0x3  << MDCM_CFG_DC_ECC_OFFSET)
#define MDCM_CFG_DLMB_MASK	(0x7  << MDCM_CFG_DLMB_OFFSET)
#define MDCM_CFG_DLMSZ_MASK	(0x1f << MDCM_CFG_DLMSZ_OFFSET)
#define MDCM_CFG_ULM_2BANK_MASK	(0x1  << MDCM_CFG_ULM_2BANK_OFFSET)
#define MDCM_CFG_DLM_ECC_MASK	(0x3  << MDCM_CFG_DLM_ECC_OFFSET)

#define CCTL_REG_UCCTLBEGINADDR_NUM	0x80b
#define CCTL_REG_UCCTLCOMMAND_NUM	0x80c

#define MCACHE_CTL_CCTL_SUEN_OFFSET	8
#define MMSC_CFG_CCTLCSR_OFFSET		16
#define MISA_20_OFFSET				20

#define MCACHE_CTL_CCTL_SUEN_MASK	(0x1 << MCACHE_CTL_CCTL_SUEN_OFFSET)
#define MMSC_CFG_CCTLCSR_MASK		(0x1 << MMSC_CFG_CCTLCSR_OFFSET)
#define MISA_20_MASK				(0x1 << MISA_20_OFFSET)

enum sbi_ext_andes_fid {
	SBI_EXT_ANDES_GET_MCACHE_CTL_STATUS = 0,
	SBI_EXT_ANDES_GET_MMISC_CTL_STATUS,
	SBI_EXT_ANDES_SET_MCACHE_CTL,
	SBI_EXT_ANDES_SET_MMISC_CTL,
	SBI_EXT_ANDES_ICACHE_OP,
	SBI_EXT_ANDES_DCACHE_OP,
	SBI_EXT_ANDES_L1CACHE_I_PREFETCH,
	SBI_EXT_ANDES_L1CACHE_D_PREFETCH,
	SBI_EXT_ANDES_NON_BLOCKING_LOAD_STORE,
	SBI_EXT_ANDES_WRITE_AROUND,
	SBI_EXT_ANDES_SET_PMA,
	SBI_EXT_ANDES_FREE_PMA,
	SBI_EXT_ANDES_PROBE_PMA,
	SBI_EXT_ANDES_DCACHE_WBINVAL_ALL,
	SBI_EXT_ANDES_GET_MICM_CTL_STATUS,
	SBI_EXT_ANDES_GET_MDCM_CTL_STATUS,
	SBI_EXT_ANDES_GET_MMSC_CTL_STATUS,
	SBI_EXT_ANDES_GET_MISA_CTL_STATUS,
};


#define custom_csr_write(csr_num,val) csr_write(csr_num,val)
/* ucctlcommand */
/* D-cache operation */
#define CCTL_L1D_VA_INVAL	0
#define CCTL_L1D_VA_WB		1
#define CCTL_L1D_VA_WBINVAL	2

/* L1 I-cache , D-cache */
#define CACHE_CTL_offIC_EN  0   /* Enable I-cache */
#define CACHE_CTL_offDC_EN  1   /* Enable D-cache */
#define CACHE_CTL_mskIC_EN  ( 0x1  << CACHE_CTL_offIC_EN )
#define CACHE_CTL_mskDC_EN  ( 0x1  << CACHE_CTL_offDC_EN )


/* L2 cache */
#define L2_CACHE_CTL_mskCEN 1
/* L2 cache registers */
#define L2C_REG_CFG_OFFSET	0
#define L2C_REG_CTL_OFFSET	0x8
#define L2C_HPM_C0_CTL_OFFSET	0x10
#define L2C_HPM_C1_CTL_OFFSET	0x18
#define L2C_HPM_C2_CTL_OFFSET	0x20
#define L2C_HPM_C3_CTL_OFFSET	0x28
#define L2C_REG_C0_CMD_OFFSET	0x40
#define L2C_REG_C0_ACC_OFFSET	0x48
#define L2C_REG_C1_CMD_OFFSET	0x50
#define L2C_REG_C1_ACC_OFFSET	0x58
#define L2C_REG_C2_CMD_OFFSET	0x60
#define L2C_REG_C2_ACC_OFFSET	0x68
#define L2C_REG_C3_CMD_OFFSET	0x70
#define L2C_REG_C3_ACC_OFFSET	0x78
#define L2C_REG_STATUS_OFFSET	0x80
#define L2C_REG_C0_HPM_OFFSET	0x200

/* L2 CCTL status */
#define CCTL_L2_STATUS_IDLE	0
#define CCTL_L2_STATUS_PROCESS	1
#define CCTL_L2_STATUS_ILLEGAL	2
/* L2 CCTL status cores mask */
#define CCTL_L2_STATUS_C0_MASK	0xF
#define CCTL_L2_STATUS_C1_MASK	0xF0
#define CCTL_L2_STATUS_C2_MASK	0xF00
#define CCTL_L2_STATUS_C3_MASK	0xF000

/* L2 cache operation */
#define CCTL_L2_PA_INVAL	0x8
#define CCTL_L2_PA_WB		0x9
#define CCTL_L2_PA_WBINVAL	0xA
#define CCTL_L2_WBINVAL_ALL	0x12

#define L2C_HPM_PER_CORE_OFFSET		0x8
#define L2C_REG_PER_CORE_OFFSET		0x10
#define CCTL_L2_STATUS_PER_CORE_OFFSET	4
#define L2C_REG_CN_CMD_OFFSET(n)	\
	L2C_REG_C0_CMD_OFFSET + (n * L2C_REG_PER_CORE_OFFSET)
#define L2C_REG_CN_ACC_OFFSET(n)	\
	L2C_REG_C0_ACC_OFFSET + (n * L2C_REG_PER_CORE_OFFSET)
#define CCTL_L2_STATUS_CN_MASK(n)	\
	CCTL_L2_STATUS_C0_MASK << (n * CCTL_L2_STATUS_PER_CORE_OFFSET)
#define L2C_HPM_CN_CTL_OFFSET(n)	\
	L2C_HPM_C0_CTL_OFFSET + (n * L2C_HPM_PER_CORE_OFFSET)
#define L2C_REG_CN_HPM_OFFSET(n)	\
	L2C_REG_C0_HPM_OFFSET + (n * L2C_HPM_PER_CORE_OFFSET)
